### ISSUE TITLE
Error:  cargo build 

### ISSUE THREAD

**Issue by ardeshir** [oxidecomputer/propolis#457]
## Error 
```
Compiling propolis v0.1.0 (/root/propolis/lib/propolis)
thread 'rustc' panicked at 'allocating stack failed with: Resource temporarily unavailable (os error 11)', /cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:168:21
stack backtrace:
   0: 0xfffffc7fe649e976 - std::backtrace_rs::backtrace::libunwind::trace::hc349f16080b9e1a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: 0xfffffc7fe649e976 - std::backtrace_rs::backtrace::trace_unsynchronized::h74ff4139f45bdeea
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0xfffffc7fe649e976 - std::sys_common::backtrace::_print_fmt::h1da3ce8656aaae22
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3: 0xfffffc7fe649e976 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he0eb18f3602360ea
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4: 0xfffffc7fe64fcffb - core::fmt::write::h8ef151b63f4a641d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5: 0xfffffc7fe6493144 - std::io::Write::write_fmt::h323b687cd8583296
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6: 0xfffffc7fe649e750 - std::sys_common::backtrace::_print::h4fa79144a2b5d494
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7: 0xfffffc7fe649e750 - std::sys_common::backtrace::print::h13950d0c448898a2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8: 0xfffffc7fe64a1190 - std::panicking::default_hook::{{closure}}::hc00f8a73bdcd502c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9: 0xfffffc7fe64a0ea3 - std::panicking::default_hook::he9acbfcf076e5fbc
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10: 0xfffffc7fdb06ac19 - <unknown>
  11: 0xfffffc7fe64a1997 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h25aa2c03f3f857cb
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
  12: 0xfffffc7fe64a1997 - std::panicking::rust_panic_with_hook::ha18432c291108e47
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
  13: 0xfffffc7fe64a1716 - std::panicking::begin_panic_handler::{{closure}}::h4645986a55c3ef2b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  14: 0xfffffc7fe649edd9 - std::sys_common::backtrace::__rust_end_short_backtrace::h6107fb71e173f9a5
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  15: 0xfffffc7fe64a1481 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  16: 0xfffffc7fe646a8f3 - core::panicking::panic_fmt::h863016252fdb1147
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  17: 0xfffffc7fe0da174e - <unknown>
  18: 0xfffffc7fdf9a8f62 - <unknown>
  19: 0xfffffc7fdb298163 - <unknown>
  20: 0xfffffc7fdb29f125 - <unknown>
  21: 0xfffffc7fdb2997a5 - <unknown>
  22: 0xfffffc7fdb155517 - <unknown>
  23: 0xfffffc7fdb1f03dc - <unknown>
  24: 0xfffffc7fdb11c1bb - <unknown>
  25: 0xfffffc7fdb1e36ba - <unknown>
  26: 0xfffffc7fdb0b5442 - <unknown>
  27: 0xfffffc7fdb06f9c8 - <unknown>
  28: 0xfffffc7fdb080ffc - <unknown>
  29: 0xfffffc7fdb074d14 - <unknown>
  30: 0xfffffc7fdb0752e6 - <unknown>
  31: 0xfffffc7fe64aada9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h58560a1484b4ff3c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  32: 0xfffffc7fe64aada9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2b6f32302a822c72
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  33: 0xfffffc7fe64aada9 - std::sys::unix::thread::Thread::new::thread_start::h0604336de98f7b8b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  34: 0xfffffc7fe5d22567 - _thrp_setup
  35: 0xfffffc7fe5d228b0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.70.0 (90c541806 2023-05-31) running on x86_64-unknown-illumos

note: compiler flags: --crate-type lib -C panic=abort -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `crucible` (lib)
```
[Machine AMI](https://ardeshir.io/omnios)

**Comment by pfmooney** [comment]
How much RAM was available on the system where you were attempting this build?  It looks like rustc may have run short on memory.

**Comment by ardeshir** [comment]
> ::memstat
Page Summary                Pages                MB  %Tot
------------     ----------------  ----------------  ----
Kernel                     192549               752   38%
Boot pages                    131                 0    0%
ZFS File Data              119904               468   24%
Anon                        23092                90    5%
Exec and libs                 884                 3    0%
Page cache                   4332                16    1%
Free (cachelist)            72783               284   14%
Free (freelist)             93728               366   18%

Total                      507403              1982
Physical                   507402              1982
>

# vmstat
 kthr      memory            page            disk          faults      cpu
 r b w   swap  free  re  mf pi po fr de sr bk ro -- --   in   sy   cs us sy
id
 0 0 0 389596 640276 639 3284 1 0 13  0 3662 7 7  0  0 3199 2200  377  2  1
98

**Comment by pfmooney** [comment]
2GB is almost certainly too small to build it.  I'd suggest starting at around 8GB or more. (And make sure adequate swap is configured on the system as well)

**Comment by jclulow** [comment]
Even if you can't increase the RAM you definitely need to increase the swap.  What swap do you have configured now?

```
swap -lh
swap -sh
```

**Comment by ardeshir** [comment]
@pfmooney  : 
I've rebuilt the image with t3.large 8Gib, and it that's not enough will keep pushing the bank, until it builds :) 

@jclulow : 
root@univrs:~# swap -sh
total: 64.91M allocated + 18.04M reserved = 82.94M used, 6.77G available

**Comment by jclulow** [comment]
Can you also do:

```
swap -lh
```

It seems like you don't have a swap partition.  I would add one, like so:

```
zfs create -V 16G rpool/swap
echo '/dev/zvol/dsk/rpool/swap - - swap - no -' >> /etc/vfstab
/sbin/swapadd
```

**Comment by ardeshir** [comment]
success 👍  thank you!

**root@univrs:~#  swap -lh** 
```
swapfile             dev    swaplo   blocks     free
/dev/zvol/dsk/rpool/swap 263,1        4K   16.00G   16.00G
```
-  Built with 8GiB 

```
   Compiling progenitor v0.2.1-dev (https://github.com/oxidecomputer/progenitor?branch=main#4c16647c)
   Compiling crucible-common v0.0.1 (https://github.com/oxidecomputer/crucible?rev=f78832dc7ca48bce53f23de00d557bc9320a933f#f78832dc)
   Compiling omicron-common v0.1.0 (https://github.com/oxidecomputer/omicron?branch=main#09fe4714)
   Compiling crucible-protocol v0.0.0 (https://github.com/oxidecomputer/crucible?rev=f78832dc7ca48bce53f23de00d557bc9320a933f#f78832dc)
   Compiling nexus-client v0.1.0 (https://github.com/oxidecomputer/omicron?branch=main#09fe4714)
   Compiling dns-service-client v0.1.0 (https://github.com/oxidecomputer/omicron?branch=main#09fe4714)
   Compiling propolis-client v0.1.0 (/root/propolis/lib/propolis-client)
   Compiling oximeter-producer v0.1.0 (https://github.com/oxidecomputer/omicron?branch=main#09fe4714)
   Compiling internal-dns v0.1.0 (https://github.com/oxidecomputer/omicron?branch=main#09fe4714)
   Compiling propolis v0.1.0 (/root/propolis/lib/propolis)
   Compiling propolis-server v0.1.0 (/root/propolis/bin/propolis-server)
   Compiling propolis-standalone v0.1.0 (/root/propolis/bin/propolis-standalone)
   Compiling propolis-cli v0.1.0 (/root/propolis/bin/propolis-cli)
    Finished dev [unoptimized + debuginfo] target(s) in 13m 01s
```
 **root@univrs:~/propolis/target/debug# ./propolis-cli --help**
 
```
A simple CLI tool to manipulate propolis-server

Usage: propolis-cli [OPTIONS] --server <SERVER> <COMMAND>

Commands:
  new         Create a new propolis instance
  get         Get the properties of a propolis instance
  state       Transition the instance to a new state
  serial      Drop to a Serial console connected to the instance
  migrate     Migrate instance to new propolis-server
  monitor     Monitor an instance's state in real time
  inject-nmi  Inject an NMI into the instance
  help        Print this message or the help of the given subcommand(s)

Options:
  -s, --server <SERVER>  propolis-server address
  -p, --port <PORT>      propolis-server port [default: 12400]
  -d, --debug            Enable debugging
  -h, --help             Print help
  -V, --version          Print version
```
**root@univrs:~/propolis/target/debug# ./propolis-server --help**

```
An HTTP server providing access to Propolis

Usage: propolis-server <COMMAND>

Commands:
  open-api  Generates the OpenAPI specification
  run       Runs the Propolis server
  help      Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
  ```
